[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vidreadpy"
version = "0.1.0"
authors = [
  { name="David Sarkisyan", email="you@example.com" },
]
description = "Лёгкая библиотека для чтения видео на Python через FFmpeg (без OpenCV)"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["video", "ffmpeg", "frames", "metadata", "reader"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Multimedia :: Video",
]
dependencies = [
  "ffmpeg-python>=0.2.0",
  "numpy>=1.24",
]

[project.urls]
Homepage = "https://github.com/davidsarkisyan280-cyber/vidreadpy"
Issues = "https://github.com/davidsarkisyan280-cyber/vidreadpy/issues"

[project.optional-dependencies]
dev = ["pytest", "ruff"]

# Ключевой момент: собираем «плоский» пакет из модулей в корне
[tool.setuptools]
py-modules = ["reader", "utils"]
